import { BiAdjust } from 'react-icons/bi';

export const categories = [
  { name: '미국 여행', icon: <BiAdjust /> },
  { name: '프랑스 여행', icon: <BiAdjust /> },
  { name: '독일 여행', icon: <BiAdjust /> },
  { name: '스페인 여행', icon: <BiAdjust /> },
  { name: '이탈리아 여행', icon: <BiAdjust /> },
  { name: '노르웨이 여행', icon: <BiAdjust /> },
  { name: '스웨덴 여행', icon: <BiAdjust /> },
  { name: '캐나다 여행', icon: <BiAdjust /> },
  { name: '인도 여행', icon: <BiAdjust /> },
  { name: '네팔 여행', icon: <BiAdjust /> },
  { name: '싱가폴 여행', icon: <BiAdjust /> },
  { name: '일본 여행', icon: <BiAdjust /> },
  { name: '한국 여행', icon: <BiAdjust /> },
  { name: '베트남 여행', icon: <BiAdjust /> },
  { name: '러시아 여행', icon: <BiAdjust /> },
  { name: '말레이시아 여행', icon: <BiAdjust /> },
  { name: '호주 여행', icon: <BiAdjust /> },
  { name: '네덜란드 여행', icon: <BiAdjust /> },
  { name: '태국 여행', icon: <BiAdjust /> },
  { name: '두바이 여행', icon: <BiAdjust /> },
  { name: '중국 여행', icon: <BiAdjust /> },
];
