import { BiAdjust } from 'react-icons/bi';

export const categories = [
  { name: '미국', icon: <BiAdjust /> },
  { name: '프랑스', icon: <BiAdjust /> },
  { name: '독일', icon: <BiAdjust /> },
  { name: '스페인', icon: <BiAdjust /> },
  { name: '이탈리아', icon: <BiAdjust /> },
  { name: '노르웨이', icon: <BiAdjust /> },
  { name: '스웨덴', icon: <BiAdjust /> },
  { name: '캐나다', icon: <BiAdjust /> },
  { name: '인도', icon: <BiAdjust /> },
  { name: '네팔', icon: <BiAdjust /> },
  { name: '싱가폴', icon: <BiAdjust /> },
  { name: '일본', icon: <BiAdjust /> },
  { name: '한국', icon: <BiAdjust /> },
  { name: '베트남', icon: <BiAdjust /> },
  { name: '러시아', icon: <BiAdjust /> },
  { name: '말레이시아', icon: <BiAdjust /> },
  { name: '호주', icon: <BiAdjust /> },
  { name: '네덜란드', icon: <BiAdjust /> },
  { name: '태국', icon: <BiAdjust /> },
  { name: '두바이', icon: <BiAdjust /> },
  { name: '중국', icon: <BiAdjust /> },
];
