import { BiAdjust } from 'react-icons/bi';

export const categories = [
  { name: '빠니보틀', icon: <BiAdjust /> },
  { name: '곽튜브', icon: <BiAdjust /> },
  { name: '초마드', icon: <BiAdjust /> },
  { name: '희철리즘', icon: <BiAdjust /> },
  { name: '집나간햄지', icon: <BiAdjust /> },
  { name: 'KBS여행 걸어서 세계속으로', icon: <BiAdjust /> },
  { name: '대륙남TV', icon: <BiAdjust /> },
  { name: '여락이들_', icon: <BiAdjust /> },
  { name: '체코채', icon: <BiAdjust /> },
  { name: '노마드션', icon: <BiAdjust /> },
  { name: '차박차박', icon: <BiAdjust /> },
  { name: '잰잰바리', icon: <BiAdjust /> },
  { name: '세나,집순이의 세계여행', icon: <BiAdjust /> },
  { name: '가든의 세계여행', icon: <BiAdjust /> },
  { name: '유일랜드', icon: <BiAdjust /> },
  { name: '홍고고', icon: <BiAdjust /> },
  { name: '또 떠나는 남자', icon: <BiAdjust /> },
  { name: '뜨랑낄로', icon: <BiAdjust /> },
  { name: '쏘이', icon: <BiAdjust /> },
  { name: '여행가 제이', icon: <BiAdjust /> },
  { name: '원지의 하루', icon: <BiAdjust /> },
];
